.PHONY: all build release clean deps install uninstall restorer

PREFIX ?= /usr/local
BINDIR = $(PREFIX)/bin

# Restorer paths
RESTORER_LIB = target/release/libcrust_restorer.a
RESTORER_ELF = crust-restorer/restorer.elf
RESTORER_BIN = crust-restorer/restorer_blob.bin
RESTORER_RS = src/restorer_blob.rs

all: build

build:
	cargo build

release: restorer
	cargo build --release

# Build the restorer blob (no_std PIE binary injected into target process)
restorer: $(RESTORER_RS)

$(RESTORER_RS): crust-restorer/src/lib.rs crust-restorer/Cargo.toml crust-syscall/src/*.rs
	@echo "=== Building crust-restorer blob ==="
	@cargo build -p crust-restorer --release
	@if [ ! -f "$(RESTORER_LIB)" ]; then \
		echo "ERROR: Library not found at $(RESTORER_LIB)"; \
		exit 1; \
	fi
	@echo "✅ Built staticlib"
	@echo ""
	@echo "=== Linking into PIE executable ==="
	@ld -pie \
		--eh-frame-hdr \
		-z noexecstack \
		-z relro \
		-z now \
		--gc-sections \
		-e _start \
		-o $(RESTORER_ELF) \
		--whole-archive $(RESTORER_LIB) --no-whole-archive \
		--strip-all
	@echo "✅ Linked PIE executable: $(RESTORER_ELF)"
	@echo ""
	@echo "=== Checking for relocations ==="
	@if readelf -r $(RESTORER_ELF) | grep -E "\.text" | grep -q "R_X86_64"; then \
		echo "⚠️  WARNING: Found relocations in .text"; \
		readelf -r $(RESTORER_ELF) | grep -E "\.text" | head -20; \
	else \
		echo "✅ Zero relocations in .text! Option 1 works!"; \
	fi
	@echo ""
	@echo "=== Extracting .text section ==="
	@objcopy -O binary \
		--only-section=.text \
		$(RESTORER_ELF) \
		$(RESTORER_BIN)
	@BLOB_SIZE=$$(stat -c%s $(RESTORER_BIN)); \
	echo "Blob size: $$BLOB_SIZE bytes"; \
	if [ $$BLOB_SIZE -gt 204800 ]; then \
		echo "⚠️  WARNING: Blob larger than 200KB"; \
	else \
		echo "✅ Blob size acceptable"; \
	fi
	@echo ""
	@echo "=== Generating Rust byte array ==="
	@echo '//! Autogenerated restorer blob' > $(RESTORER_RS)
	@echo '//!' >> $(RESTORER_RS)
	@echo '//! Generated by Makefile' >> $(RESTORER_RS)
	@echo '//! DO NOT EDIT MANUALLY' >> $(RESTORER_RS)
	@echo '' >> $(RESTORER_RS)
	@echo 'pub const RESTORER_BLOB: &[u8] = &[' >> $(RESTORER_RS)
	@xxd -i < $(RESTORER_BIN) >> $(RESTORER_RS)
	@echo '];' >> $(RESTORER_RS)
	@echo '' >> $(RESTORER_RS)
	@echo 'pub const RESTORER_SIZE: usize = RESTORER_BLOB.len();' >> $(RESTORER_RS)
	@echo "✅ Generated $(RESTORER_RS)"

clean:
	cargo clean
	@rm -f $(RESTORER_ELF) $(RESTORER_BIN) $(RESTORER_RS)
	@rm -f *.o
	@echo "Cleaned restorer artifacts"

deps:
	@echo "Installing system dependencies (requires sudo)..."
	sudo apt-get update
	sudo apt-get install -y protobuf-compiler libprotobuf-dev

install: release
	@echo "Installing crust to $(BINDIR)..."
	install -D -m 755 target/release/crust $(BINDIR)/crust
	@echo "crust installed successfully. Run 'crust --help' to get started."

uninstall:
	@echo "Removing crust from $(BINDIR)..."
	rm -f $(BINDIR)/crust
	@echo "crust uninstalled."

run:
	bash test/restore.sh